---
Name: devtoolkit
After:
  - 'framework/*'
  - 'cms/*'
---
# A smarter global partial key
SSViewer:
  global_key: '$CurrentReadingMode, $ContentLocale, $SiteConfig.ID'
ModelAdmin:
  extensions:
    - DevToolkitAdminExtension
SiteConfig:
  extensions:
    - DevToolkitSiteConfigExtension
Director:
  rules:
    'devtoolkitassets': 'DevToolkitAssetsController'
    'robots.txt': 'DevRobotsController'
LeftAndMain:
  extensions:
    - DevToolkitLeftAndMainExtension
DevToolkitAssetsController:
  enable_audit: true
  cms_access_ignore_rules: true
  admin_ignore_rules: true
  rules:
    'private': 'logged-in'
    'owner' : 'owner'
# ---
# Only:
#  classexists: 'FluentExtension'
# ---
# ContentController:
#  extensions:
#    - TranslatableActionsControllerExtension